#+title: Odv Request
Integration of the odv-request transaction
#+begin_src bash
 λ > poetry run odv-demo blockfrost preprod send-odv-request --help
usage: python main.py [{blockfrost,ogmios}] [{preprod,mainnet}] send-odv-request [-h] [--funds-to-send FUNDSTOSEND]

Generate a request for information by prepaying the Charli3 oracles.

options:
  -h, --help            show this help message and exit
  --funds-to-send FUNDSTOSEND
                        Minimum C3 payment amount for the generation of an oracle-feed.
#+end_src

Generating an ODV request involves sending a pre-calculated amount of C3 tokens to the ODV contract. When this is done, the backend configured for that contract will detect the payment of the C3 tokens and, within approximately one minute, the ODV contract will generate a new oracle feed.

The pre-calculated amount of C3 tokens is determined based on the internal configuration of the ODV contract (specifically, the aggstate datum). These C3 tokens are used to compensate each individual C3 node in the network and to pay the contract administrator for monitoring and maintenance.

The swap contract supports the operation of sending an ODV request using the following command:

#+begin_src bash
poetry run odv-demo blockfrost preprod send-odv-request
#+end_src

This command automatically calculates the required amount of C3 tokens needed to generate the aggregation.

Let's use the following toy ODV oracle contract as an example to determine the minimum C3 tokens required. Its internal oracle configuration is as follows:
#+begin_src yml
oracle_settings:
  os_node_list:
    [
       "49bd983d12353a48d39ad15212220ebd71dd3f897eb29ab89f3cb58e",
       "8e9ed3986a773db2420b0604357a65f5d9d26d094279918ad405fdca"
    ]
  os_updated_nodes: 10000 # 100%
  os_node_fee_price:
    node_fee: 1500000 # 1.5 C3
    aggregate_fee: 2500000 # 2.5 C3
    platform_fee: 1000000 # 1 C3
#+end_src
